### ISSUE TITLE
Can the published nuget package be updated

### ISSUE THREAD

**Issue by mleech** [testfairy/testfairy-xamarin#3]
Could the latest version (2.1.5) be published to nuget.org? The latest published version is 2.1.1.
Thanks.

**Comment by ghuntley** [comment]
Dinged support@testfairy.com moments ago. Let's give it one more day before forking.

**Comment by Im-PJ** [comment]
and now can the latest version 2.2.0 be pushed to nuget.org?

**Comment by ghuntley** [comment]
Seems the best way to interact with these peeps is to email the support@ address. GitHub is unmonitored.

**Comment by Im-PJ** [comment]
@ghuntley  yes they responded over email. Its updated now.
