### ISSUE TITLE
Version TestFairy.Xamarin.2.15.0 ins't published

### ISSUE THREAD

**Issue by jzeferino** [testfairy/testfairy-xamarin#5]
Hello, there was a release of the version 2.15.0 in the github but it ins't yet published in the nuget feed. Can you guys take care of it please?

**Comment by jzeferino** [comment]
Pinging on this, @vijaysharm, @gmegidish.

**Comment by vijaysharm** [comment]
Hi @jzeferino, I apologize about the delay, however, it seemed as though Travis had some issues pushing the release to NuGet. I've since re-ran the build and it appears to have been pushed. Thanks for letting us know!
